// ===============================================================================
// DATA
// Below data will hold all of the possible friends.
// ===============================================================================


var friends = [
   {
      "name":"Leonardo",
      "photo":"http://images.forbes.com/media/2010/12/16/1216_leonardo-dicaprio-high-earning_485x340.jpg",
      "scores":[
         "3",
         "1",
         "5",
         "2",
         "4",
         "2",
         "1",
         "2",
         "3",
         "5"
      ]
   },
   {
      "name":"Matt",
      "photo":"https://timedotcom.files.wordpress.com/2015/09/matt-damon3.jpg?quality=85&w=814",
      "scores":[
         "3",
         "3",
         "3",
         "2",
         "2",
         "2",
         "4",
         "4",
         "4",
         "4"
      ]
   },
   {
      "name":"Tom",
      "photo":"http://i1-news.softpedia-static.com/images/news2/Actors-Rushing-to-Play-Steve-Jobs-Despite-Dropouts-467046-2.jpg",
      "scores":[
         "4",
         "3",
         "2",
         "1",
         "2",
         "3",
         "4",
         "5",
         "4",
         "3"
      ]
   },
   {
      "name":"Angelia",
      "photo":"http://the10bestreview.com/wp-content/uploads/2014/08/Angelina-Jolie.jpg",
      "scores":[
         "2",
         "1",
         "4",
         "2",
         "1",
         "3",
         "5",
         "2",
         "4",
         "1"
      ]
   },
	{
	   "name":"Jennifer",
	   "photo":"http://top101news.com/wp-content/uploads/2015/08/jennifer-aniston-most-beautiful-hollywood-actress-2016.jpg",
	   "scores":[
	      "5",
	      "5",
	      "5",
	      "4",
	      "4",
	      "3",
	      "2",
	      "1",
	      "1",
	      "1"
	   ]
	},
	{
	   "name":"Emma",
	   "photo":"http://media2.intoday.in/indiatoday/images/stories/emma-watson_650_070814102526.jpg",
	   "scores":[
	      "1",
	      "2",
	      "3",
	      "4",
	      "5",
	      "3",
	      "1",
	      "1",
	      "3",
	      "2"
	   ]
	},
	{
	   "name":"Tammana",
	   "photo":"http://sim01.in.com/a34c5ff13943a801f9d1b038cc6300f2_ft_xl.jpg",
	   "scores":[
	      "1",
	      "2",
	      "2",
	      "4",
	      "2",
	      "3",
	      "1",
	      "1",
	      "4",
	      "2"
	   ]
	},
	{
	   "name":"Jessica",
	   "photo":"http://sizzlingsuperstars.com/wp-content/uploads/2016/09/Jessica-Alba-7-768x480.jpg",
	   "scores":[
	      "1",
	      "2",
	      "3",
	      "3",
	      "5",
	      "3",
	      "1",
	      "2",
	      "3",
	      "2"
	   ]
	}
]

// Here we export the array. This makes it accessible to other files using require. 
module.exports = friends;